config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :medicines
   resources :user_sessions 

  match 'login' => "user_sessions#new",      :as => :login,via:[:get,:post]
  match 'logout' => "user_sessions#destroy", :as => :logout,via:[:delete,:post]


  resources :users  # give us our some normal resource routes for users
  resource :user, :as => 'account'  # a convenience route

 match 'signup' => 'users#new', :as => :signup,via:[:get,:post]


  root :to => 'user_sessions#new'

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/medicine.rb
class Medicine < ActiveRecord::Base
    #resourcify  
	belongs_to :user

	def self.search(search)
  where("name LIKE ?", "%#{search}%") 
 end
end

  

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_action :require_user
  before_action :set_medicine, only: [:show, :edit, :update, :destroy]
  require 'date'
  # GET /medicines
  # GET /medicines.json
  def index
    #@medicines = Medicine.all
    @medicines = current_user.medicines
    if params[:search]
    @medicines = @medicines.search(params[:search]).order("created_at DESC")
   else
    @medicines = current_user.medicines
   end
   @exp_medicine = Medicine.where("expiry_date > ? And expiry_date < ? && user_id = ?",Date.today - 2.days,Date.today + 2,current_user.id)
   UserMailer.send_report(@exp_medicine).deliver if @exp_medicine.present?

   #@medicines.each do |med|
    #  expiry_date_diff = (med.expiry_date.to_date - Date.today).to_i
     #    if expiry_date_diff <= 2  
     #end
   #end 
 end

 

  # GET /medicines/1
  # GET /medicines/1.json
  def show
  end

  # GET /medicines/new
  def new
    @medicine = Medicine.new
  end

  # GET /medicines/1/edit
  def edit
  end

  # POST /medicines
  # POST /medicines.json
  def create
    @medicine = Medicine.new(medicine_params.merge!({:user_id => current_user.id}))

    respond_to do |format|
      if @medicine.save
        format.html { redirect_to @medicine, notice: 'Medicine was successfully created.' }
        format.json { render :show, status: :created, location: @medicine }
      else
        format.html { render :new }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicines/1
  # PATCH/PUT /medicines/1.json
  def update
    respond_to do |format|
      if @medicine.update(medicine_params.merge!({:user_id => current_user.id}))
        format.html { redirect_to @medicine, notice: 'Medicine was successfully updated.' }
        format.json { render :show, status: :ok, location: @medicine }
      else
        format.html { render :edit }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicines/1
  # DELETE /medicines/1.json
  def destroy
    @medicine.destroy
    respond_to do |format|
      format.html { redirect_to medicines_url, notice: 'Medicine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicine
      @medicine = Medicine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medicine_params
      params.require(:medicine).permit(:name, :quantity, :selling_quantity, :expiry_date, :price)
    end
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/views/medicines/_form.html.erb
<%= form_for(@medicine) do |f| %>
  <% if @medicine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medicine.errors.count, "error") %> prohibited this medicine from being saved:</h2>

      <ul>
      <% @medicine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
      <label for="name">Name:</label>
      <%=f.text_field :name,:class=>"form-control",:placeholder=>"Enter Name"%>
    </div>
    <div class="form-group">
      <label for="quantity">quantity:</label>
      <%=f.text_field :quantity,:class=>"form-control",:placeholder=>"Enter quantity"%>
    </div>
    <div class="form-group">
      <label for="selling_quantity">selling_quantity:</label>
      <%=f.text_field :selling_quantity,:class=>"form-control",:placeholder=>"Enter selling_quantity"%>
    </div>
    <div class="form-group">
      <label for="price">price:</label>
      <%=f.number_field :price,:class=>"form-control",:placeholder=>"Re-Enter price"%>
    </div>
     <div class="form-group">
      <label for="expiry_date">expiry date:</label>
      <%=f.date_select :expiry_date,:class=>"form-control",:placeholder=>"Re-Enter date"%>
    </div>

    <%= f.submit 'submit',:class=>"btn btn-default" %>
  <% end %>
</div>

app/views/medicines/edit.html.erb
<h1>Editing Medicine</h1>

<%= render 'form' %>

<%= link_to 'Show', @medicine %> |
<%= link_to 'Back', medicines_path %>

app/views/medicines/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<style>
body {
    background-image: url('/assets/medicine.jpg');

}
</style>
<h2 style="background-color:black">
Welcome to Medicines Management System <%= current_user.name %>
</h2>
<%= form_tag(medicines_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Medicines" %>
<%= submit_tag "Search" %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Selling quantity</th>
      <th>Expiry date</th>
      <th>Price</th>
      <th>show</th>
      <th>edit</th>
      <th>delete</th>
      <th>Buy</th>
     
    </tr>
  </thead>

  <tbody>
    <% @medicines.each do |medicine| %>
      <tr>
        <td><%= medicine.name %></td>
        <td><%= medicine.quantity %></td>
        <td><%= medicine.selling_quantity %></td>
        <td><%= medicine.expiry_date %></td>
        <td><%= medicine.price %></td>
        <td><%= link_to 'Show', medicine %></td>
        <td><%= link_to 'Edit', edit_medicine_path(medicine) %></td>
        <td><%= link_to 'Destroy', medicine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Buy', medicine %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br/>

<%= link_to 'New Medicine', new_medicine_path %>
<%= link_to 'Logout', logout_url, method: :delete %>

app/views/medicines/new.html.erb
<h1>New Medicine</h1>

<%= render 'form' %>

<%= link_to 'Back', medicines_path %>

app/views/medicines/send_report.pdf.erb
<div class="container">
<p><h4><b>Details Of Your medicine:</b></h4></p>
<table class="table">
	<% @exp_medicine.each do |exp_medicine| %>
   <thead><th><p>Name : <%= exp_medicine.name %><br/></p></th></thead>
   <thead><th><p>Price: <%= exp_medicine.price %><br/></p></th></thead>
   <thead><th><p>quantity: <%= exp_medicine.quantity %><br/></p></th></thead>
   <thead><th><p>selling quantity:<%= exp_medicine.selling_quantity%><br/></p></th></thead>
   <thead><th><p>expiry date: <%= exp_medicine.expiry_date%><br/></p></th></thead>
   <%end%>
</table>
</div>

app/views/medicines/show.html.erb
<div class="container">
<p><h4><b>Details Of Your medicine:</b></h4></p>
<table class="table">
   <thead><th><p>Name of medicine: <%= @medicine.name %><br/></p></th></thead>
   <thead><th><p>Price: <%= @medicine.price %><br/></p></th></thead>
   <thead><th><p>quantity: <%= @medicine.quantity %><br/></p></th></thead>
   <thead><th><p>selling quantity:<%= @medicine.selling_quantity%><br/></p></th></thead>
   <thead><th><p>expiry date: <%= @medicine.expiry_date%><br/></p></th></thead>
   
</table>
</div>
<%= link_to 'Edit', edit_medicine_path(@medicine) %> |
<%= link_to 'Back', medicines_path %>
<div>