config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :medicines
   resources :user_sessions 

  match 'login' => "user_sessions#new",      :as => :login,via:[:get,:post]
  match 'logout' => "user_sessions#destroy", :as => :logout,via:[:delete,:post]


  resources :users  # give us our some normal resource routes for users
  resource :user, :as => 'account'  # a convenience route

 match 'signup' => 'users#new', :as => :signup,via:[:get,:post]


  root :to => 'user_sessions#new'

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

 before_filter :find_id, :only=>[:edit,:update,:show,:destroy]

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(allow)
    if @user_session.save
      flash[:notice] = "user log in successfully"
      redirect_to medicines_path
    else
       flash[:notice] = "error"
      redirect_to new_user_session_path
    end
  end

  def destroy
    if current_user_session.present?
      
      current_user_session.destroy
      redirect_to new_user_session_path
    end
  end

  private

  def find_id
    @user_session = UserSession.find(params[:id])
  end
  
  def allow
    params.require(:user_session).permit(:email, :password)
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
 <div class="container">

 <%= form_for @user_session, url: user_sessions_path, method: :post, html: { class: 'form-horizontal', role: 'form' } do |f| %>  

 <% if @user_session.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <p><%= pluralize(@user_session.errors.count, "error") %>  can not be save saved:</p>

      <ul>
      <% @user_session.errors.full_messages.each do |message| %>
        <div class="alert alert-danger">
          <li><%= message %></li>
      </div>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
      <label for="title">Email:</label>
      <%=f.text_field :email,:class=>"form-control",:placeholder=>"Enter Email"%>
  </div>
  <div class="form-group">
      <label for="title">Password:</label>
      <%=f.password_field :password,:class=>"form-control",:placeholder=>"Enter Password"%>
  </div>
  <%= f.submit 'Login',:class=>"btn btn-default" %>
  <% end %>
  <br/>
  <%=link_to 'Sign_up',new_user_path, :class=>"btn btn-success"%>
   

</div>
 
 